#!/usr/bin/env python3
"""Builds src/font_data.cpp: the bitmap fonts the firmware draws text with.

The display library's own fonts have no Cyrillic, so the letters are rendered here from DejaVu
(free licence) into small 4-bit-per-pixel pictures. Run again only to change sizes or characters:

    python3 tools/make_font.py
"""
import pathlib
from PIL import ImageFont

DEJAVU = pathlib.Path('/usr/share/fonts/truetype/dejavu')
TEXT = [chr(c) for c in range(32, 127)] + [chr(c) for c in range(0x410, 0x450)] + list('Ёё·×«»…←')
DIGITS = list('0123456789')
FONTS = [  # name, file, pixel size, characters
    ('FONT_S', 'DejaVuSans.ttf', 12, TEXT),
    ('FONT_M', 'DejaVuSans-Bold.ttf', 15, TEXT),
    ('FONT_L', 'DejaVuSansCondensed-Bold.ttf', 26, TEXT),
    ('FONT_D', 'DejaVuSans-Bold.ttf', 11, DIGITS),
]

def build(name, file, size, chars):
    font = ImageFont.truetype(str(DEJAVU / file), size)
    ascent, descent = font.getmetrics()
    data, glyphs = bytearray(), []
    for ch in sorted(set(chars)):
        x0, y0, x1, y1 = font.getbbox(ch)
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        mask = font.getmask(ch, mode='L')
        if mask.size != (w, h):
            w, h = mask.size
        offset = len(data)
        nibbles = [mask.getpixel((x, y)) >> 4 for y in range(h) for x in range(w)]
        if len(nibbles) % 2:
            nibbles.append(0)
        for k in range(0, len(nibbles), 2):
            data.append(nibbles[k] << 4 | nibbles[k + 1])
        glyphs.append((ord(ch), w, h, x0, y0, int(round(font.getlength(ch))), offset))
    out = [f'// {name}: {file} at {size} px, {len(glyphs)} characters, {len(data)} bytes of pixels',
           f'static const uint8_t {name}_PIXELS[] = {{']
    for k in range(0, len(data), 24):
        out.append('  ' + ','.join(str(b) for b in data[k:k + 24]) + ',')
    out.append('};')
    out.append(f'static const Glyph {name}_GLYPHS[] = {{')
    for code, w, h, xo, yo, adv, off in glyphs:
        out.append(f'  {{{code},{w},{h},{xo},{yo},{adv},{off}}},')
    out.append('};')
    out.append(f'const Font {name} = {{{name}_GLYPHS, {name}_PIXELS, {len(glyphs)}, {ascent + descent}, {ascent}}};')
    return '\n'.join(out), len(data)

def main():
    parts, total = [], 0
    for spec in FONTS:
        text, size = build(*spec)
        parts.append(text); total += size
    body = ('// Generated by tools/make_font.py. Do not edit by hand.\n'
            '#include "ui.h"\n\n' + '\n\n'.join(parts) + '\n')
    target = pathlib.Path(__file__).resolve().parent.parent / 'src' / 'font_data.cpp'
    target.write_text(body)
    print(f'{target}: {total} bytes of pixels')

main()
